export { default as LandingHero } from './LandingHero';
export { default as LandingAbout } from './LandingAbout';
export { default as LandingRoadmap } from './LandingRoadmap';
export { default as LandingTeam } from './LandingTeam';
export { default as LandingMintNFT } from './LandingMintNFT';
export { default as LandingGiveaways} from './LandingGiveaways';
export { default as LandingEquipment } from './LandingEquipment';
export { default as LandingDamage } from './LandingDamage';
export { default as LandingNFTs } from './LandingNFTs';
export { default as LandingNFT } from './LandingNFT';
